### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by slivingston** [pixmoving-moveit/kuaikai_perception#1]
Can you add a license to this repository? At least this requires:

* declaring the license in the README and
* providing a link to it, either to a LICENSE file in the sourcetree or to some reference site, like https://opensource.org/

From what I remember, we are using the [BSD 3-clause](https://opensource.org/licenses/BSD-3-Clause) for all work in this organization.

**Comment by themathgeek13** [comment]
Hi Scott, I've added the BSD-3 License now.
